### ISSUE TITLE
Merge plan to develop branch

### ISSUE THREAD

**Issue by kasongoyo** [CodeTanzania/emis-dashboard#132]
@BenMaruchu the develop branch does not have plan changes? If I remember last time we agreed that  we should merge develop branch incrementally? Is this still in effect?

**Comment by BenMaruchu** [comment]
Hello @kasongoyo , regarding merging changes from plans there was a milestone I want to achieve before merging it. I have a plan to merge changes soon this week.

**Comment by kasongoyo** [comment]
@BenMaruchu ok. Please do it so that we can benefit with some changes that are global i.e needed by others.
