### ISSUE TITLE
Eslint fix for settings 

### ISSUE THREAD

**Issue by kasongoyo** [CodeTanzania/emis-dashboard#133]
@mkumbobeaty the changes from you that got merged to develop branch a while ago had eslint errors? Did you fix them and submit new request? If not then can you do so because this make develop branch dirty and other can't actual merge their changes. But how did those changes pass through travis @BenMaruchu

**Comment by BenMaruchu** [comment]
@kasongoyo  what are the errors in eslint? can you take a screenshot cause Travis doesn't have show any error

**Comment by kasongoyo** [comment]
<img width="1307" alt="screen shot 2018-11-21 at 15 00 12" src="https://user-images.githubusercontent.com/1956062/48839948-35524580-ed9e-11e8-9d0c-6e0b067a049b.png">

@BenMaruchu I am getting that error after pulling from develop and run `lint:fix`

**Comment by BenMaruchu** [comment]
@kasongoyo  I think you haven't install dependencies

**Comment by kasongoyo** [comment]
@BenMaruchu That's correct. Thanks for prompt reply.
