### ISSUE TITLE
Add breadcrumb starting from plan>activity>sop

### ISSUE THREAD

**Issue by kasongoyo** [CodeTanzania/emis-dashboard#138]
I propose to Add breadcrumb starting from plan>activity>sop to make the UI more informative. I feel like it will be very common for user to move between plan, activity and sop so enabling easy way to so will make it more better

**Comment by BenMaruchu** [comment]
Thanks for the issue, This is already included on the Milestone for plan 0.2.0. Based on this issue #77, #69
