### ISSUE TITLE
Remove OK button on SOP Details popup

### ISSUE THREAD

**Issue by navish** [CodeTanzania/emis-dashboard#140]
![github-issues](https://user-images.githubusercontent.com/8484784/49648902-92a1f400-fa38-11e8-98b6-59bfd7240637.JPG)

**Comment by navish** [comment]
@BenMaruchu  The Cancel button does not make much sense here. Either change the text to Close or convert it to Edit button.

**Comment by BenMaruchu** [comment]
I think converting it to edit button makes more sense.
