### ISSUE TITLE
color for hover and active selected stakeholder should be as per mockups

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/emis-dashboard#25]
![screenshot from 2018-09-13 19-44-08](https://user-images.githubusercontent.com/1610857/45502775-87b72a80-b78d-11e8-89c3-fd5de02b330f.png)

**Comment by kasongoyo** [comment]
I tried with the mockup color especially those color you pointed out last time i.e #f9f9f9 but the color contrast was weak and as the result I chose different color. I can fix it by looking into another shade of gray which will maintain the contrast
