### ISSUE TITLE
Setup proposed folder structure for the project

### ISSUE THREAD

**Issue by BenMaruchu** [CodeTanzania/emis-dashboard#4]

**Comment by BenMaruchu** [comment]
@kasongoyo & @Mloweedgar & @navish 

I think this has to be an open discussion.

From my side I think we should arrange folders feature-wise and not functional-wise. So that once the project has grown large it will be easy to navigate around

e.g 
- :file_folder: Feature
    - :file_folder: Components(stateless)
    - :file_folder: HOC(statefull)
    - :file_folder: reducers
    - :file_folder: actions

**Comment by kasongoyo** [comment]
Hi Benson, I completely agree with your proposal especially if we follow the structure explained here https://medium.com/@alexmngn/how-to-better-organize-your-react-applications-2fd3ea1920f1. I have used it on number of projects and I have seen it's real make navigation easy.

**Comment by Mloweedgar** [comment]
I also Agree with @BenMaruchu.

**Comment by navish** [comment]
@BenMaruchu I'm cool with it.
