### ISSUE TITLE
Setting up middleware for async actions

### ISSUE THREAD

**Issue by Mloweedgar** [CodeTanzania/emis-dashboard#5]

**Comment by Mloweedgar** [comment]
@BenMaruchu , @kasongoyo , @navish 
Which middleware are we going to use for async actions?
I suggest using [redux-observable(Epics)](https://redux-observable.js.org/docs/basics/Epics.html) you can read this blog [post](https://medium.com/dailyjs/using-redux-observable-to-handle-asynchronous-logic-in-redux-d49194742522) to learn why I made this choice, I will be happy to hear what are your ideas on this.

**Comment by BenMaruchu** [comment]
I believe this has already been done.
