### ISSUE TITLE
There should be right margin on create plan button(toolbar action) same as left marging on left filter

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/emis-dashboard#57]
Toolbar Action:
![screenshot from 2018-09-25 14-01-46](https://user-images.githubusercontent.com/1610857/46010536-b2797b00-c0cb-11e8-960a-dd57ba2281a0.png)

Filter:
![screenshot from 2018-09-25 14-03-12](https://user-images.githubusercontent.com/1610857/46010663-2a47a580-c0cc-11e8-8560-114b205a492c.png)

**Comment by BenMaruchu** [comment]
This already implemented
