### ISSUE TITLE
During planning I suspect we wont need to have summary view unless we view the plan in execution

### ISSUE THREAD

**Issue by lykmapipo** [CodeTanzania/emis-dashboard#80]
![screenshot from 2018-09-25 15-43-04](https://user-images.githubusercontent.com/1610857/46015018-cdeb8280-c0d9-11e8-92c7-2c4150ecc9d1.png)

**Comment by BenMaruchu** [comment]
This is subjected to alot of changes as of now

**Comment by BenMaruchu** [comment]
Yes the UI for activity have changed. So there won't be any Summary during planning phase
